Shop/Controllers/DetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Shop.DataBase;
using Shop.Models;

namespace Shop.Controllers
{
    public class DetailController : Controller
    {
        // GET: Detail
        public ActionResult Index(int productId)
        {
            List<Product> productList;

            using (var db = new ShopDB())
            {
                productList = db.MASTER_PRODUCT
                    .Join(db.GENRE, p => p.GENRE_ID, g => g.GENRE_ID, (p, g) => new { p, g })
                    .Join(db.MASTER_CATEGORY, mp => mp.p.CATEGORY_ID, c => c.CATEGORY_ID, (mp, c) => new { mp, c })
                    .Where(p => p.mp.p.PRODUCT_ID == productId)
                    .Select(x => new Product
                    {
                        ProductId = x.mp.p.PRODUCT_ID,
                        ProductName = x.mp.p.PRODUCT_NAME,
                        CategoryId = x.mp.p.CATEGORY_ID,
                        CategoryName = x.c.CATEGORY_NAME,
                        GenreName = x.mp.g.GENRE_NAME,
                        Character = x.mp.p.CHARACTER,
                        MagazineName = x.mp.p.MAGAZINE_NAME,
                        Publisher = x.mp.p.PUBLISHER,
                        Price = x.mp.p.PRICE
                    })
                    .ToList();
                foreach (var p in productList)
                {
                    if (productId.Equals(p.ProductId))
                    {
                        return View(productList);
                    }
                }
                return RedirectToAction("Index","Search");
            }
        }
    }
}

Shop/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Shop.DataBase;
using Shop.Models;

namespace Shop.Controllers
{
    public class SearchController : Controller
    {
        
        public ActionResult Index()
        {

            List<Product> msList;
            using (var db = new ShopDB())
            {
                msList = db.MASTER_PRODUCT
                .Join(db.GENRE,p => p.GENRE_ID,g => g.GENRE_ID,(p,g) => new {p,g})
                .Join(db.MASTER_CATEGORY,mp => mp.p.CATEGORY_ID,mc => mc.CATEGORY_ID,(mp,mc) => new {mp,mc})
                .Select(x => new Product {
                    ProductId = x.mp.p.PRODUCT_ID,
                    ProductName = x.mp.p.PRODUCT_NAME,
                    CategoryId = x.mp.p.CATEGORY_ID,
                    CategoryName = x.mc.CATEGORY_NAME,
                    GenreName = x.mp.g.GENRE_NAME,
                    Character = x.mp.p.CHARACTER,
                    MagazineName = x.mp.p.MAGAZINE_NAME,
                    Publisher = x.mp.p.PUBLISHER,
                    Price = x.mp.p.PRICE
                })
                .ToList();
            }
            return View(msList);
        } 
        public ActionResult Result(string genreId)
        {
           
            List<Product> productList;
            
            using (var db = new ShopDB())
            {
                productList = db.MASTER_PRODUCT
                    .Join(db.GENRE,p => p.GENRE_ID,g => g.GENRE_ID,(p,g) => new { p,g})
                    .Join(db.MASTER_CATEGORY,mp => mp.p.CATEGORY_ID,c => c.CATEGORY_ID,(mp,c) => new {mp,c})
                    .Where(p => p.mp.p.GENRE_ID == genreId)
                    .Select(x => new Product {
                        ProductId = x.mp.p.PRODUCT_ID,
                        ProductName = x.mp.p.PRODUCT_NAME,
                        CategoryId = x.mp.p.CATEGORY_ID,
                        CategoryName = x.c.CATEGORY_NAME,
                        GenreName = x.mp.g.GENRE_NAME,
                        Character = x.mp.p.CHARACTER,
                        MagazineName = x.mp.p.MAGAZINE_NAME,
                        Publisher = x.mp.p.PUBLISHER,
                        Price = x.mp.p.PRICE
                    })
                    .ToList();

            }
            return View(productList);
        }
   
    }
}

Shop/Views/Search/Index.cshtml
@using Shop.DataBase
@using Shop.Models
@model List<Product>

@{
    ViewBag.Title = "Search";
}

<h1 class="text-center">商品検索</h1>

<form method="post" action="/Search/Result">
    <div class="text-center">

        <div class="form-group input-lg">

            <select name="genreId">

                <option value="G1">少年漫画</option>

                <option value="G2">少女漫画</option>

            </select>

            <button type="submit" class="btn btn-primary">検索</button>
         </div>

    </div>
</form>

<p class="small text-muted text-right">詳細を知りたい方は、「商品名」をクリックしてください</p>

<table class="table">

    <tr class="bg-info">

        <th>ジャンル</th>
        <th>カテゴリ</th>
        <th>ID</th>
        <th>商品名</th>

    </tr>

    @foreach (var product in Model)

    {
        <tr>
            <td>@product.GenreName</td>
            <td>@product.CategoryName</td>
            <td>@product.ProductId</td>
            <td><a href="@Url.Action("Index","Detail",new {product.ProductId})">@product.ProductName</a></td>
        </tr>

    }
</table>
<form action="/Menu/Index">
    <div class="form-group">
        <div class="text-right">
            <button type="submit" class="btn btn-primary">メニューへ戻る</button>
        </div>
    </div>
</form>

Shop/Views/Search/Result.cshtml
@using Shop.DataBase
@using Shop.Models
@model List<Product>

@{
    ViewBag.Title = "Result";
}
<h1 class="text-center">商品検索</h1>

<p class="small text-muted text-right">詳細を知りたい方は、商品名をクリックしてください</p>

    <table class="table">
        <tr class="bg-info">
            <th>ジャンル</th>
            <th>カテゴリ</th>
            <th>ID</th>
            <th>商品名</th>
        </tr>

        @foreach (var product in Model)

        {
            <tr>
                <td>@product.GenreName</td>
                <td>@product.CategoryName</td>
                <td>@product.ProductId</td>
                <td><a href="@Url.Action("Index","Detail",new {product.ProductId})">@product.ProductName</a></td>
            </tr>

        }

    </table>
    <form action="/Search/Index">
        <div class="form-group">
            <div class="text-right">
            <button type="submit" class="btn btn-primary">再検索</button>
            </div>
        </div>
    </form>